[package]
name = "hello_world"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.92"
publish = false

[dependencies]
yt-dlp = "1.4.8"
rfd = "0.17.2"
tokio = { version = "1", features = ["full"]}

eframe = "0.33.3"
egui = "0.33.3"
egui_extras = "0.33.3"
env_logger = "0.11.8"
